version: '3.8'
services:
  app:
    image: my-laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: "base64:TiVNIEKjUDHVbJ5zXOWk2wVbHBQVRD3a0xo/fwRV8g0="
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  dbdata:
